Implemented Generate Shopping List features
klaudiaRajs/KcalAndGIHelper pull request #1
Opened 2024-02-17 09:45 UTC by lucasadamski

1. Generate Shopping List for single day.
2. Generate Shopping List for muliple days marked with check-boxes.

2024-02-18 11:05 UTC, klaudiaRajs requested changes

2024-02-18 11:05 UTC, klaudiaRajs commented on Diabetic/Controllers/DietDayController.cs
> +                return View("MyErrorPage", new ErrorPageDTO() { Body = HelperErrorMessages.PL_SHOPPING_LIST_NO_DAYS_SELECTED });
Może warto to zamienić na użycie toastra?

2024-02-18 11:05 UTC, klaudiaRajs commented on Diabetic/Controllers/DietDayController.cs
> +            LoadAllRecipesForDayByDayId(id, viewModel);
W linijkach od 59 do 63 do viewModelu przypisywane były wartości. Później przekazujesz ten viewModel jako parametr, ale te wartości nie są nigdzie zwracane, nie przypisujesz ich ponownie do viewModelu.

2024-02-18 11:05 UTC, klaudiaRajs commented on Diabetic/Controllers/DietDayController.cs
> +                LoadAllRecipesForDayByDayId(dayId, viewModel);
Ponownie, wartości nie są przypisywane z powrotem do viewModelu

2024-02-18 11:05 UTC, klaudiaRajs commented on Diabetic/Controllers/DietDayController.cs
> +                    Product = group.Select(n => n.Product).FirstOrDefault(),
Super!

2024-02-18 11:05 UTC, klaudiaRajs commented on Diabetic/Views/DietDay/Index.cshtml
> +                <form method="post" asp-controller="DietDay" asp-action="Index">
Super z wykorzystaniem tagów asp!

2024-02-18 11:05 UTC, klaudiaRajs commented on Diabetic/Views/DietDay/ShoppingList.cshtml
> +            <th scope="col">ID</th>
Ja bym tutaj nie pakowałam ID - ten widok będzie czysto użytkowy, pewnie do późniejszego wydruku. ID w sklepie nie będzie nam potrzebne ;)

2024-02-18 11:05 UTC, klaudiaRajs commented on Diabetic/wwwroot/js/site.js
> +// Write your JavaScript code.
Zwracaj uwagę czy nie commitujesz plików bez żadnych zmian (takich jak np. białe znaki czy tak jak tutaj).

2024-02-19 06:37 UTC, lucasadamski commented on Diabetic/wwwroot/js/site.js
> +// Write your JavaScript code.
Ok.

2024-02-19 06:40 UTC, lucasadamski commented on Diabetic/Views/DietDay/ShoppingList.cshtml
> +            <th scope="col">ID</th>
Done.

2024-02-19 06:40 UTC, lucasadamski commented on Diabetic/Views/DietDay/Index.cshtml
> +                <form method="post" asp-controller="DietDay" asp-action="Index">
Dzięki :)

2024-02-19 06:40 UTC, lucasadamski commented on Diabetic/Controllers/DietDayController.cs
> +                    Product = group.Select(n => n.Product).FirstOrDefault(),
Dzięki :)

2024-02-19 06:49 UTC, lucasadamski commented on Diabetic/Controllers/DietDayController.cs
> +            LoadAllRecipesForDayByDayId(id, viewModel);
viewModel jest modyfikowany wewnątrz metody.

2024-02-19 06:49 UTC, lucasadamski commented on Diabetic/Controllers/DietDayController.cs
> +                LoadAllRecipesForDayByDayId(dayId, viewModel);
viewModel jest modyfikowany wewnątrz metody.

2024-02-19 09:56 UTC, lucasadamski commented on Diabetic/Controllers/DietDayController.cs
> +                return View("MyErrorPage", new ErrorPageDTO() { Body = HelperErrorMessages.PL_SHOPPING_LIST_NO_DAYS_SELECTED });
Done.

2024-02-19 17:58 UTC, klaudiaRajs approved these changes

2024-02-19 17:58 UTC, klaudiaRajs commented on Diabetic/Views/DietDay/Index.cshtml
> +                console.log("Znalazłem zaznaczony");
Uwaga na zostawione console.logi!!

2024-02-19 17:59 UTC, merged